[build]
  command = "/bin/bash ./netlify-command.sh"
  publish = "assets"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    
[[redirects]]
  from = "/*"
  to = "https://pymedphys.com"
